theme: jekyll-theme-cayman
og-title: Wizards 2022
og-description: Leaderboard

theme_color:  rgb(25,55,71)
font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i
